name: dpr-fr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.1
  - aom=3.9.1
  - attr=2.5.2
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - colorama=0.4.6
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.4.0
  - ffmpeg=8.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - glslang=16.1.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - icu=78.1
  - imath=3.2.2
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - jasper=4.2.8
  - joblib=1.5.3
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.26.3
  - libabseil=20250512.1
  - libaec=1.1.4
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.7
  - libclang13=21.1.7
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.12.0
  - libopengl=1.7.0
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=18.1
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.41.3
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - mpg123=1.32.9
  - ncurses=6.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.4.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openjph=0.26.0
  - openldap=2.6.10
  - openssl=3.6.0
  - pango=1.56.4
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - py-opencv=4.12.0
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - qt6-main=6.10.1
  - rav1e=0.7.1
  - readline=8.3
  - sdl2=2.32.56
  - sdl3=3.2.28
  - setuptools=80.9.0
  - shaderc=2025.5
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tzdata=2025c
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
    - accelerate==0.34.2
    - anyio==4.12.0
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - diffusers==0.30.3
    - einops==0.8.1
    - exceptiongroup==1.3.1
    - facenet-pytorch==2.6.0
    - filelock==3.20.1
    - fsspec==2025.12.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - idna==3.11
    - importlib-metadata==8.7.1
    - jinja2==3.1.6
    - kagglehub==0.3.13
    - markupsafe==3.0.3
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.1.105
    - packaging==25.0
    - pandas==2.3.3
    - pillow==10.2.0
    - psutil==7.2.0
    - pyyaml==6.0.3
    - regex==2025.11.3
    - requests==2.32.5
    - safetensors==0.7.0
    - scikit-learn==1.7.2
    - scipy==1.15.2
    - sympy==1.13.1
    - tokenizers==0.20.3
    - torch==2.2.2+cu121
    - torchvision==0.17.2+cu121
    - transformers==4.45.2
    - triton==2.2.0
    - typing-extensions==4.15.0
    - urllib3==2.6.2
    - zipp==3.23.0
prefix: /home/kalifadan/miniconda3/envs/dpr-fr
