name: dpr-fr
channels:
  - defaults
dependencies:
  - pillow
  - pandas
  - python=3.10
  - opencv
  - tqdm
  - pip
  - pyyaml
  - numpy
  - scikit-learn
prefix: /home/kalifadan/miniconda3/envs/dpr-fr
